// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using edu_connect_backend.Infrastructure.Persistence.Context;

#nullable disable

namespace edu_connect_backend.Migrations
{
    [DbContext(typeof(ConnectionContext))]
    [Migration("20251217181527_AdicionandoAlunosTurmas")]
    partial class AdicionandoAlunosTurmas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("edu_connect_backend.Model.Aluno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("dataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("matricula");

                    b.Property<int?>("turma_id")
                        .HasColumnType("int")
                        .HasColumnName("turma_id");

                    b.Property<int?>("turmaid")
                        .HasColumnType("int")
                        .HasColumnName("turmaid");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<int>("usuarioid")
                        .HasColumnType("int")
                        .HasColumnName("usuarioid");

                    b.HasKey("id");

                    b.HasIndex("turmaid");

                    b.HasIndex("usuarioid");

                    b.ToTable("alunos");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Turma", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("anoLetivo")
                        .HasColumnType("int")
                        .HasColumnName("ano_letivo");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.HasKey("id");

                    b.ToTable("turmas");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cpf");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("fotoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("foto_url");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<string>("perfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("perfil");

                    b.Property<string>("senhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("senha_hash");

                    b.HasKey("id");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Aluno", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Turma", "turma")
                        .WithMany()
                        .HasForeignKey("turmaid");

                    b.HasOne("edu_connect_backend.Model.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("turma");

                    b.Navigation("usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
