// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using edu_connect_backend.Infrastructure.Persistence.Context;

#nullable disable

namespace edu_connect_backend.Migrations
{
    [DbContext(typeof(ConnectionContext))]
    [Migration("20260114023040_BugfixDashboardProfessor")]
    partial class BugfixDashboardProfessor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("edu_connect_backend.Model.Aluno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("dataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("matricula");

                    b.Property<int?>("turmaId")
                        .HasColumnType("int")
                        .HasColumnName("turma_id");

                    b.Property<int>("usuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("id");

                    b.HasIndex("turmaId");

                    b.HasIndex("usuarioId");

                    b.ToTable("aluno");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Aviso", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("dataPostagem")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_postagem");

                    b.Property<string>("mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mensagem");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titulo");

                    b.Property<int?>("turmaId")
                        .HasColumnType("int")
                        .HasColumnName("turma_id");

                    b.HasKey("id");

                    b.HasIndex("turmaId");

                    b.ToTable("aviso");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Disciplina", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("codigo");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.HasKey("id");

                    b.ToTable("disciplina");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Entrega", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("alunoId")
                        .HasColumnType("int")
                        .HasColumnName("aluno_id");

                    b.Property<string>("arquivoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("arquivo_url");

                    b.Property<DateTime>("dataEntrega")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_entrega");

                    b.Property<int>("materialId")
                        .HasColumnType("int")
                        .HasColumnName("material_id");

                    b.HasKey("id");

                    b.HasIndex("alunoId");

                    b.HasIndex("materialId");

                    b.ToTable("entrega");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Evento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("dataFim")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("dataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_inicio");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titulo");

                    b.Property<int?>("turmaId")
                        .HasColumnType("int")
                        .HasColumnName("turma_id");

                    b.Property<int>("usuarioCriadorId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_criador_id");

                    b.HasKey("id");

                    b.HasIndex("turmaId");

                    b.HasIndex("usuarioCriadorId");

                    b.ToTable("evento");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Frequencia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("alunoId")
                        .HasColumnType("int")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime>("dataAula")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_aula");

                    b.Property<int>("disciplinaId")
                        .HasColumnType("int")
                        .HasColumnName("disciplina_id");

                    b.Property<bool>("presente")
                        .HasColumnType("bit")
                        .HasColumnName("presente");

                    b.HasKey("id");

                    b.HasIndex("alunoId");

                    b.HasIndex("disciplinaId");

                    b.ToTable("frequencia");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Material", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("dataEntrega")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_entrega");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<decimal?>("notaMaxima")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("nota_maxima");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titulo");

                    b.Property<int>("topicoId")
                        .HasColumnType("int")
                        .HasColumnName("topico_id");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.HasKey("id");

                    b.HasIndex("topicoId");

                    b.ToTable("material");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Nota", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("alunoId")
                        .HasColumnType("int")
                        .HasColumnName("aluno_id");

                    b.Property<int>("bimestre")
                        .HasColumnType("int")
                        .HasColumnName("bimestre");

                    b.Property<DateTime>("dataLancamento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_lancamento");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.Property<int>("turmaDisciplinaId")
                        .HasColumnType("int")
                        .HasColumnName("turma_disciplina_id");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("id");

                    b.HasIndex("alunoId");

                    b.HasIndex("turmaDisciplinaId");

                    b.ToTable("nota");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Notificacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("dataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_criacao");

                    b.Property<bool>("lida")
                        .HasColumnType("bit")
                        .HasColumnName("lida");

                    b.Property<string>("mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mensagem");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titulo");

                    b.Property<int>("usuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("id");

                    b.HasIndex("usuarioId");

                    b.ToTable("notificacao");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Professor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("especialidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("especialidade");

                    b.Property<string>("matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("matricula");

                    b.Property<int>("usuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("id");

                    b.HasIndex("usuarioId");

                    b.ToTable("professor");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Topico", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titulo");

                    b.Property<int>("turmaDisciplinaId")
                        .HasColumnType("int")
                        .HasColumnName("turma_disciplina_id");

                    b.HasKey("id");

                    b.HasIndex("turmaDisciplinaId");

                    b.ToTable("topico");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Turma", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("anoLetivo")
                        .HasColumnType("int")
                        .HasColumnName("ano_letivo");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.HasKey("id");

                    b.ToTable("turma");
                });

            modelBuilder.Entity("edu_connect_backend.Model.TurmaDisciplina", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("disciplinaId")
                        .HasColumnType("int")
                        .HasColumnName("disciplina_id");

                    b.Property<int>("professorId")
                        .HasColumnType("int")
                        .HasColumnName("professor_id");

                    b.Property<int>("turmaId")
                        .HasColumnType("int")
                        .HasColumnName("turma_id");

                    b.HasKey("id");

                    b.HasIndex("disciplinaId");

                    b.HasIndex("professorId");

                    b.HasIndex("turmaId");

                    b.ToTable("turma_disciplina");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cpf");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("fotoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("foto_url");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<string>("perfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("perfil");

                    b.Property<string>("senhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("senha_hash");

                    b.HasKey("id");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Aluno", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Turma", "turma")
                        .WithMany()
                        .HasForeignKey("turmaId");

                    b.HasOne("edu_connect_backend.Model.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("turma");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Aviso", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Turma", "turma")
                        .WithMany()
                        .HasForeignKey("turmaId");

                    b.Navigation("turma");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Entrega", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Aluno", "aluno")
                        .WithMany()
                        .HasForeignKey("alunoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("edu_connect_backend.Model.Material", "material")
                        .WithMany()
                        .HasForeignKey("materialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("aluno");

                    b.Navigation("material");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Evento", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Turma", "turma")
                        .WithMany()
                        .HasForeignKey("turmaId");

                    b.HasOne("edu_connect_backend.Model.Usuario", "usuarioCriador")
                        .WithMany()
                        .HasForeignKey("usuarioCriadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("turma");

                    b.Navigation("usuarioCriador");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Frequencia", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Aluno", "aluno")
                        .WithMany()
                        .HasForeignKey("alunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edu_connect_backend.Model.Disciplina", "disciplina")
                        .WithMany()
                        .HasForeignKey("disciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aluno");

                    b.Navigation("disciplina");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Material", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Topico", "topico")
                        .WithMany("materiais")
                        .HasForeignKey("topicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("topico");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Nota", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Aluno", "aluno")
                        .WithMany()
                        .HasForeignKey("alunoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("edu_connect_backend.Model.TurmaDisciplina", "turmaDisciplina")
                        .WithMany()
                        .HasForeignKey("turmaDisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aluno");

                    b.Navigation("turmaDisciplina");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Notificacao", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Professor", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Topico", b =>
                {
                    b.HasOne("edu_connect_backend.Model.TurmaDisciplina", "turmaDisciplina")
                        .WithMany("topicos")
                        .HasForeignKey("turmaDisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("turmaDisciplina");
                });

            modelBuilder.Entity("edu_connect_backend.Model.TurmaDisciplina", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Disciplina", "disciplina")
                        .WithMany()
                        .HasForeignKey("disciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edu_connect_backend.Model.Professor", "professor")
                        .WithMany()
                        .HasForeignKey("professorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edu_connect_backend.Model.Turma", "turma")
                        .WithMany()
                        .HasForeignKey("turmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("disciplina");

                    b.Navigation("professor");

                    b.Navigation("turma");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Topico", b =>
                {
                    b.Navigation("materiais");
                });

            modelBuilder.Entity("edu_connect_backend.Model.TurmaDisciplina", b =>
                {
                    b.Navigation("topicos");
                });
#pragma warning restore 612, 618
        }
    }
}
