// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using edu_connect_backend.Infrastructure.Persistence.Context;

#nullable disable

namespace edu_connect_backend.Migrations
{
    [DbContext(typeof(ConnectionContext))]
    [Migration("20260305033952_AdicionandoModelsMatricula")]
    partial class AdicionandoModelsMatricula
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("edu_connect_backend.DTO.GraficoBarrasDTO", b =>
                {
                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("label");

                    b.Property<decimal>("value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("value");

                    b.ToTable("grafico_barras_dto");
                });

            modelBuilder.Entity("edu_connect_backend.DTO.GraficoPizzaDTO", b =>
                {
                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("label");

                    b.Property<int>("value")
                        .HasColumnType("int")
                        .HasColumnName("value");

                    b.ToTable("grafico_pizza_dto");
                });

            modelBuilder.Entity("edu_connect_backend.DTO.KPIsCoordenadorDTO", b =>
                {
                    b.Property<decimal>("mediaGeralEscola")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("media_geral_escola");

                    b.Property<int>("totalAlunos")
                        .HasColumnType("int")
                        .HasColumnName("total_alunos");

                    b.Property<int>("totalProfessores")
                        .HasColumnType("int")
                        .HasColumnName("total_professores");

                    b.ToTable("kpis_coordenador_dto");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Aluno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("dataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("matricula");

                    b.Property<int?>("turmaId")
                        .HasColumnType("int")
                        .HasColumnName("turma_id");

                    b.Property<int>("usuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("id");

                    b.HasIndex("turmaId");

                    b.HasIndex("usuarioId");

                    b.ToTable("aluno");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Aviso", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("dataPostagem")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_postagem");

                    b.Property<string>("mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mensagem");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titulo");

                    b.Property<int?>("turmaId")
                        .HasColumnType("int")
                        .HasColumnName("turma_id");

                    b.HasKey("id");

                    b.HasIndex("turmaId");

                    b.ToTable("aviso");
                });

            modelBuilder.Entity("edu_connect_backend.Model.ConfiguracaoVaga", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("anoLetivo")
                        .HasColumnType("int")
                        .HasColumnName("ano_letivo");

                    b.Property<string>("serie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("serie");

                    b.Property<string>("turno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("turno");

                    b.Property<int>("vagasTotais")
                        .HasColumnType("int")
                        .HasColumnName("vagas_totais");

                    b.Property<decimal>("valorMensalidade")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_mensalidade");

                    b.HasKey("id");

                    b.ToTable("configuracao_vaga");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Disciplina", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("codigo");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.HasKey("id");

                    b.ToTable("disciplina");
                });

            modelBuilder.Entity("edu_connect_backend.Model.DocumentoMatricula", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("caminhoArquivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("caminho_arquivo");

                    b.Property<string>("nomeOriginalArquivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_original_arquivo");

                    b.Property<string>("observacaoRejeicao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observacao_rejeicao");

                    b.Property<int>("solicitacaoMatriculaId")
                        .HasColumnType("int")
                        .HasColumnName("solicitacao_matricula_id");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.Property<bool>("validado")
                        .HasColumnType("bit")
                        .HasColumnName("validado");

                    b.HasKey("id");

                    b.HasIndex("solicitacaoMatriculaId");

                    b.ToTable("documento_matricula");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Entrega", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("alunoId")
                        .HasColumnType("int")
                        .HasColumnName("aluno_id");

                    b.Property<string>("arquivoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("arquivo_url");

                    b.Property<DateTime>("dataEntrega")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_entrega");

                    b.Property<int>("materialId")
                        .HasColumnType("int")
                        .HasColumnName("material_id");

                    b.HasKey("id");

                    b.HasIndex("alunoId");

                    b.HasIndex("materialId");

                    b.ToTable("entrega");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Evento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("dataFim")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("dataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_inicio");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titulo");

                    b.Property<int?>("turmaId")
                        .HasColumnType("int")
                        .HasColumnName("turma_id");

                    b.Property<int>("usuarioCriadorId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_criador_id");

                    b.HasKey("id");

                    b.HasIndex("turmaId");

                    b.HasIndex("usuarioCriadorId");

                    b.ToTable("evento");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Extracurricular", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.HasKey("id");

                    b.ToTable("extracurricular");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Frequencia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("alunoId")
                        .HasColumnType("int")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime>("dataAula")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_aula");

                    b.Property<int>("disciplinaId")
                        .HasColumnType("int")
                        .HasColumnName("disciplina_id");

                    b.Property<bool>("presente")
                        .HasColumnType("bit")
                        .HasColumnName("presente");

                    b.HasKey("id");

                    b.HasIndex("alunoId");

                    b.HasIndex("disciplinaId");

                    b.ToTable("frequencia");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Material", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("dataEntrega")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_entrega");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<decimal?>("notaMaxima")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("nota_maxima");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titulo");

                    b.Property<int>("topicoId")
                        .HasColumnType("int")
                        .HasColumnName("topico_id");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.HasKey("id");

                    b.HasIndex("topicoId");

                    b.ToTable("material");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Nota", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("alunoId")
                        .HasColumnType("int")
                        .HasColumnName("aluno_id");

                    b.Property<int>("bimestre")
                        .HasColumnType("int")
                        .HasColumnName("bimestre");

                    b.Property<DateTime>("dataLancamento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_lancamento");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.Property<int>("turmaDisciplinaId")
                        .HasColumnType("int")
                        .HasColumnName("turma_disciplina_id");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("id");

                    b.HasIndex("alunoId");

                    b.HasIndex("turmaDisciplinaId");

                    b.ToTable("nota");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Notificacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("dataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_criacao");

                    b.Property<bool>("lida")
                        .HasColumnType("bit")
                        .HasColumnName("lida");

                    b.Property<string>("mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mensagem");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titulo");

                    b.Property<int>("usuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("id");

                    b.HasIndex("usuarioId");

                    b.ToTable("notificacao");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Professor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("especialidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("especialidade");

                    b.Property<string>("matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("matricula");

                    b.Property<int>("usuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("id");

                    b.HasIndex("usuarioId");

                    b.ToTable("professor");
                });

            modelBuilder.Entity("edu_connect_backend.Model.SolicitacaoMatricula", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("codigoOtp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("codigo_otp");

                    b.Property<string>("contatoResponsavel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contato_responsavel");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("dataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_nascimento");

                    b.Property<DateTime>("dataSolicitacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_solicitacao");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("enderecoCompleto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("endereco_completo");

                    b.Property<string>("escolaridadeAnterior")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("escolaridade_anterior");

                    b.Property<string>("nomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("nomeResponsavel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_responsavel");

                    b.Property<string>("rg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rg");

                    b.Property<string>("serieDesejada")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("serie_desejada");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefone");

                    b.Property<string>("turnoDesejado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("turno_desejado");

                    b.Property<DateTime?>("validadeOtp")
                        .HasColumnType("datetime2")
                        .HasColumnName("validade_otp");

                    b.Property<decimal?>("valorMensalidade")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_mensalidade");

                    b.HasKey("id");

                    b.ToTable("solicitacao_matricula");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Topico", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titulo");

                    b.Property<int>("turmaDisciplinaId")
                        .HasColumnType("int")
                        .HasColumnName("turma_disciplina_id");

                    b.Property<int?>("turmaExtracurricularId")
                        .HasColumnType("int")
                        .HasColumnName("turma_extracurricular_id");

                    b.HasKey("id");

                    b.HasIndex("turmaDisciplinaId");

                    b.HasIndex("turmaExtracurricularId");

                    b.ToTable("topico");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Turma", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("anoLetivo")
                        .HasColumnType("int")
                        .HasColumnName("ano_letivo");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.HasKey("id");

                    b.ToTable("turma");
                });

            modelBuilder.Entity("edu_connect_backend.Model.TurmaDisciplina", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("disciplinaId")
                        .HasColumnType("int")
                        .HasColumnName("disciplina_id");

                    b.Property<int>("professorId")
                        .HasColumnType("int")
                        .HasColumnName("professor_id");

                    b.Property<int>("turmaId")
                        .HasColumnType("int")
                        .HasColumnName("turma_id");

                    b.HasKey("id");

                    b.HasIndex("disciplinaId");

                    b.HasIndex("professorId");

                    b.HasIndex("turmaId");

                    b.ToTable("turma_disciplina");
                });

            modelBuilder.Entity("edu_connect_backend.Model.TurmaExtracurricular", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("extracurricularId")
                        .HasColumnType("int")
                        .HasColumnName("extracurricular_id");

                    b.Property<int>("professorId")
                        .HasColumnType("int")
                        .HasColumnName("professor_id");

                    b.Property<int>("turmaId")
                        .HasColumnType("int")
                        .HasColumnName("turma_id");

                    b.HasKey("id");

                    b.HasIndex("extracurricularId");

                    b.HasIndex("professorId");

                    b.HasIndex("turmaId");

                    b.ToTable("turma_extracurricular");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cpf");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("fotoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("foto_url");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<string>("perfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("perfil");

                    b.Property<string>("senhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("senha_hash");

                    b.HasKey("id");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Aluno", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Turma", "turma")
                        .WithMany()
                        .HasForeignKey("turmaId");

                    b.HasOne("edu_connect_backend.Model.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("turma");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Aviso", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Turma", "turma")
                        .WithMany()
                        .HasForeignKey("turmaId");

                    b.Navigation("turma");
                });

            modelBuilder.Entity("edu_connect_backend.Model.DocumentoMatricula", b =>
                {
                    b.HasOne("edu_connect_backend.Model.SolicitacaoMatricula", "solicitacao")
                        .WithMany("documentos")
                        .HasForeignKey("solicitacaoMatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("solicitacao");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Entrega", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Aluno", "aluno")
                        .WithMany()
                        .HasForeignKey("alunoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("edu_connect_backend.Model.Material", "material")
                        .WithMany()
                        .HasForeignKey("materialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("aluno");

                    b.Navigation("material");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Evento", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Turma", "turma")
                        .WithMany()
                        .HasForeignKey("turmaId");

                    b.HasOne("edu_connect_backend.Model.Usuario", "usuarioCriador")
                        .WithMany()
                        .HasForeignKey("usuarioCriadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("turma");

                    b.Navigation("usuarioCriador");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Frequencia", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Aluno", "aluno")
                        .WithMany()
                        .HasForeignKey("alunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edu_connect_backend.Model.Disciplina", "disciplina")
                        .WithMany()
                        .HasForeignKey("disciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aluno");

                    b.Navigation("disciplina");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Material", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Topico", "topico")
                        .WithMany("materiais")
                        .HasForeignKey("topicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("topico");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Nota", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Aluno", "aluno")
                        .WithMany()
                        .HasForeignKey("alunoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("edu_connect_backend.Model.TurmaDisciplina", "turmaDisciplina")
                        .WithMany()
                        .HasForeignKey("turmaDisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aluno");

                    b.Navigation("turmaDisciplina");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Notificacao", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Professor", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Topico", b =>
                {
                    b.HasOne("edu_connect_backend.Model.TurmaDisciplina", "turmaDisciplina")
                        .WithMany("topicos")
                        .HasForeignKey("turmaDisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edu_connect_backend.Model.TurmaExtracurricular", "turmaExtracurricular")
                        .WithMany("topicos")
                        .HasForeignKey("turmaExtracurricularId");

                    b.Navigation("turmaDisciplina");

                    b.Navigation("turmaExtracurricular");
                });

            modelBuilder.Entity("edu_connect_backend.Model.TurmaDisciplina", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Disciplina", "disciplina")
                        .WithMany()
                        .HasForeignKey("disciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edu_connect_backend.Model.Professor", "professor")
                        .WithMany()
                        .HasForeignKey("professorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edu_connect_backend.Model.Turma", "turma")
                        .WithMany()
                        .HasForeignKey("turmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("disciplina");

                    b.Navigation("professor");

                    b.Navigation("turma");
                });

            modelBuilder.Entity("edu_connect_backend.Model.TurmaExtracurricular", b =>
                {
                    b.HasOne("edu_connect_backend.Model.Extracurricular", "extracurricular")
                        .WithMany()
                        .HasForeignKey("extracurricularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edu_connect_backend.Model.Professor", "professor")
                        .WithMany()
                        .HasForeignKey("professorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edu_connect_backend.Model.Turma", "turma")
                        .WithMany()
                        .HasForeignKey("turmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("extracurricular");

                    b.Navigation("professor");

                    b.Navigation("turma");
                });

            modelBuilder.Entity("edu_connect_backend.Model.SolicitacaoMatricula", b =>
                {
                    b.Navigation("documentos");
                });

            modelBuilder.Entity("edu_connect_backend.Model.Topico", b =>
                {
                    b.Navigation("materiais");
                });

            modelBuilder.Entity("edu_connect_backend.Model.TurmaDisciplina", b =>
                {
                    b.Navigation("topicos");
                });

            modelBuilder.Entity("edu_connect_backend.Model.TurmaExtracurricular", b =>
                {
                    b.Navigation("topicos");
                });
#pragma warning restore 612, 618
        }
    }
}
